import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const modules = process.env.SURVEY_READER_NODE_MODULES || '/Users/edwin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const require = createRequire(import.meta.url);
const { chromium } = require(path.join(modules, 'playwright'));
const { marked } = await import(path.join(modules, 'marked/lib/marked.esm.js'));
const file = path.join(root, 'notes/2026-09-30-self-improvement-agent-acceleration-review-zh.html');
const md = fs.readFileSync(file.replace(/html$/, 'md'), 'utf8');
const shots = process.env.SURVEY_READER_SHOTS || '/private/tmp/survey-reader-qa';
fs.mkdirSync(shots, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const errors = [], external = [];
page.on('pageerror', e => errors.push(e.message));
await page.route(/^https?:/, route => { external.push(route.request().url()); return route.abort(); });
await page.goto(pathToFileURL(file).href);
await page.evaluate(() => document.fonts.ready);
assert.equal(await page.locator('#panel-report [data-formula]').count(), 47);
assert.equal(await page.locator('.reference-list>li').count(), 53);
assert.equal(await page.locator('.chapter').count(), 10);
assert.equal(await page.locator('.katex-error').count(), 0);
assert.equal(await page.locator('code').allTextContents().then(x => x.join('|')), 'not_found|click(index=5)|contact_name');
// Reverse only presentation substitutions and compare every prose/table block.
const sourceHtml = marked.parse(md.split('\n## 参考文献\n')[0]);
const fidelity = await page.evaluate(expectedHtml => {
  const normalize = s => s.replace(/\s+/g, ' ').trim();
  const expected = new DOMParser().parseFromString(expectedHtml, 'text/html');
  const actual = document.querySelector('#panel-report').cloneNode(true);
  actual.querySelector('.panel-heading').remove(); actual.querySelector('.reading-tools').remove();
  actual.querySelectorAll('[data-source]').forEach(n => n.replaceWith(document.createTextNode(n.dataset.source)));
  actual.querySelectorAll('.citation').forEach(n => n.replaceWith(document.createTextNode(n.dataset.ref)));
  const select = 'p, li, td, th';
  const a = [...actual.querySelectorAll(select)].map(n => normalize(n.textContent));
  const e = [...expected.querySelectorAll(select)].map(n => normalize(n.textContent));
  return { actual: a.length, expected: e.length, mismatches: a.flatMap((s, i) => s === e[i] ? [] : [{ i, actual: s, expected: e[i] }]) };
}, sourceHtml);
assert.equal(fidelity.actual, fidelity.expected);
assert.deepEqual(fidelity.mismatches, []);
const expectedRefs = [...md.split('\n## 参考文献\n')[1].matchAll(/^\[(\d+)\] ([\s\S]*?)(?=\n\n\[\d+\] |$)/gm)].map(m => marked.parse(m[2].trim()));
const refsMatch = await page.evaluate(html => {
  const norm = s => s.replace(/\s+/g, ' ').trim();
  const actual = [...document.querySelectorAll('.ref-entry')].map(n => norm(n.textContent));
  const expected = html.map(s => norm(new DOMParser().parseFromString(s, 'text/html').body.textContent));
  return actual.every((s, i) => s === expected[i]);
}, expectedRefs);
assert(refsMatch);
const originalCitationUrls = [...md.split('\n## 参考文献\n')[0].matchAll(/\[\d+\]\((https?:\/\/[^)]+)\)/g)].map(m => m[1]);
assert.deepEqual(await page.locator('#panel-report .citation').evaluateAll(nodes => nodes.map(n => n.dataset.sourceUrl)), originalCitationUrls);
await page.screenshot({ path: path.join(shots, 'desktop-overview.png'), fullPage: true });
await page.locator('#slide-next').click();
assert.equal(await page.locator('.slide:visible h3').textContent(), '先比较经验存成什么');
await page.locator('.slide:visible .citation').first().click();
assert(await page.locator('#reference-dialog').isVisible());
await page.locator('#dialog-close').click();
await page.locator('#tab-methods').click();
await page.locator('[data-object-filter=world]').click();
assert.equal(await page.locator('.method-card:visible').count(), 2);
await page.locator('#method-search').fill('zzzzzzzz');
assert(await page.locator('#methods-empty').isVisible());
await page.locator('#method-search').fill('');
await page.locator('[data-object-filter=all]').click();
await page.locator('.method-card').first().locator('summary').click();
await page.screenshot({ path: path.join(shots, 'desktop-methods.png'), fullPage: false });
await page.locator('#tab-formulas').click();
await page.locator('#formula-filter').selectOption('9');
assert.equal(await page.locator('.formula-card:visible').count(), 5);
await page.screenshot({ path: path.join(shots, 'desktop-formulas.png'), fullPage: true });
await page.locator('#formula-filter').selectOption('all');
await page.locator('#formula-47 .jump').click();
assert(await page.locator('#panel-report').isVisible());
assert.equal(new URL(page.url()).hash, '#equation-47');
await page.locator('.chapter-nav [data-chapter=s3]').click();
assert(await page.locator('#panel-report').isVisible());
await page.screenshot({ path: path.join(shots, 'desktop-report.png'), fullPage: false });
await page.locator('#s3 .citation').first().click();
assert.equal(await page.locator('#dialog-source').getAttribute('href'), 'https://arxiv.org/pdf/2406.07496v1');
await page.locator('#dialog-close').click();
await page.locator('#tab-references').click();
await page.locator('#reference-search').fill('TextGrad');
assert.equal(await page.locator('.reference-list>li:visible').count(), 1);
await page.locator('#reference-search').fill('');
const viewports = [{ width: 1440, height: 1100 }, { width: 768, height: 1024 }, { width: 390, height: 844 }, { width: 320, height: 760 }];
const overflow = [];
for (const viewport of viewports) {
  await page.setViewportSize(viewport);
  for (const mode of ['overview', 'report', 'methods', 'formulas', 'references']) {
    await page.locator('#tab-' + mode).click();
    const geometry = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth }));
    if (geometry.scrollWidth > geometry.width + 1) overflow.push({ viewport, mode, ...geometry });
    if (viewport.width === 390 && ['overview','report','formulas'].includes(mode)) await page.screenshot({ path: path.join(shots, `mobile-${mode}.png`), fullPage: false });
  }
}
assert.deepEqual(overflow, []);
await page.setViewportSize({ width: 390, height: 844 });
await page.locator('#menu-toggle').click();
assert(await page.locator('#sidebar').isVisible());
await page.locator('.chapter-nav [data-chapter=s9]').click();
assert(!(await page.locator('#sidebar').isVisible()));
assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'false');
await page.emulateMedia({ media: 'print' });
assert(await page.locator('#panel-report').isVisible());
assert(await page.locator('#panel-references').isVisible());
assert(!(await page.locator('#panel-overview').isVisible()));
assert.equal(external.length, 0);
assert.deepEqual(errors, []);
await browser.close();
console.log(JSON.stringify({ status: 'passed', proseBlocks: fidelity.actual, formulas: 47, references: 53, viewports: viewports.map(v => v.width), externalRequests: external.length, javascriptErrors: errors.length, screenshots: shots }, null, 2));
