(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const data=JSON.parse($('#reader-data').textContent), evidenceMap=new Map(data.evidence.map(e=>[e.id,e])), refMap=new Map(data.refs.map(r=>[r.id,r]));
let mode='overview',large=false,evidencePage=0,lastFocus;const memory={},pageSize=15,dialog=$('#detail-dialog');
function closeDrawer(){$('#sidebar').classList.remove('open');$('#drawer-shade').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}
function view(next,scroll=true){if(!$('#panel-'+next))return;memory[mode]=scrollY;mode=next;$$('.panel').forEach(p=>p.hidden=p.id!=='panel-'+next);$$('[role=tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.mode===next));b.tabIndex=b.dataset.mode===next?0:-1;});closeDrawer();if(scroll)window.scrollTo({top:memory[next]||0,behavior:'instant'});progress();}
function go(id,panel='report'){const node=$('#'+id);if(!node)return;view(panel,false);for(let p=node.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;history.replaceState(null,'','#'+id);requestAnimationFrame(()=>{node.scrollIntoView({block:'start',behavior:'instant'});node.focus({preventScroll:true});});}
function open(html,title,origin){lastFocus=origin;$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
function showEvidence(id,origin){const e=evidenceMap.get(id);if(!e){open('<p>此编号来自其他批次，请查看原始证据台账。</p>',id,origin);return;}open(`<h3>${escapeText(e.title)}</h3><p class="muted">${escapeText(e.record||'')} ${e.legacy?'· 此前批次':''}</p>${e.html}<div class="dialog-refs">${e.url?`<a href="${escapeText(e.url)}" target="_blank" rel="noopener noreferrer">打开实际引用的原文 ↗</a>`:''}${refMap.has(e.reference)?`<button class="record-link" data-reference="${e.reference}">完整参考文献 ${e.reference}</button>`:''}</div><p class="dialog-source-note">此处展开原证据台账的记录，保留其测量条件和原审计标签，不表示本轮重新全文核验。</p>`,id+' · 证据记录',origin);}
function showReference(id,origin){const r=refMap.get(id);if(!r){open('<p>这个记录号是原稿引用的别名或此前批次记录；请通过同段的 E 编号查看来源。</p>',id,origin);return;}open(r.html+(r.url?`<p><a href="${escapeText(r.url)}" target="_blank" rel="noopener noreferrer">打开实际核读版本 ↗</a></p>`:''),id+' · 参考文献',origin);}
function escapeText(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
document.addEventListener('click',e=>{const evidence=e.target.closest('[data-evidence]');if(evidence){e.preventDefault();showEvidence(evidence.dataset.evidence,evidence);return;}const ref=e.target.closest('[data-reference]');if(ref){e.preventDefault();showReference(ref.dataset.reference,ref);return;}const a=e.target.closest('[data-audit]');if(a){e.preventDefault();go('audit-'+a.dataset.audit,'audit');return;}const c=e.target.closest('[data-chapter]');if(c){e.preventDefault();go(c.dataset.chapter);return;}const v=e.target.closest('[data-mode]');if(v){e.preventDefault();view(v.dataset.mode);return;}const t=e.target.closest('[data-table-view]');if(t){const box=t.closest('.comparison'), table=$('.table-wrap',box),cards=$('.table-records',box);table.hidden=!table.hidden;cards.hidden=!table.hidden;t.setAttribute('aria-pressed',String(!table.hidden));t.textContent=table.hidden?'切换为横向表格':'切换为逐项展开';return;}const ex=e.target.closest('[data-expand-table]');if(ex){const rows=$$('details',ex.closest('.comparison'));const all=rows.every(d=>d.open);rows.forEach(d=>d.open=!all);ex.textContent=all?'展开全部':'收起全部';}});
$('#dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(lastFocus?.isConnected&&!lastFocus.closest('[hidden]'))lastFocus.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('#menu-toggle').addEventListener('click',()=>{const b=$('#sidebar'),o=!b.classList.contains('open');b.classList.toggle('open',o);$('#drawer-shade').classList.toggle('open',o);$('#menu-toggle').setAttribute('aria-expanded',String(o));if(o)$('#drawer-close').focus();});$('#drawer-close').addEventListener('click',()=>{closeDrawer();$('#menu-toggle').focus();});$('#drawer-shade').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});
$('.view-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=$$('[role=tab]'),i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;view(tabs[n].dataset.mode);tabs[n].focus();});
$('#font-size').addEventListener('click',e=>{large=!large;document.documentElement.style.setProperty('--reading-size',large?'20px':'18px');e.currentTarget.textContent=large?'标准字号':'放大正文';});
$('#expand-all').addEventListener('click',e=>{const rows=$$('#panel-report .table-record'),all=rows.every(d=>d.open);rows.forEach(d=>d.open=!all);e.currentTarget.textContent=all?'展开本报告所有对照项':'收起本报告所有对照项';});
function renderEvidence(){const q=$('#evidence-search').value.trim().toLowerCase(),list=data.evidence.filter(e=>!q||e.search.toLowerCase().includes(q)),pages=Math.max(1,Math.ceil(list.length/pageSize));evidencePage=Math.min(evidencePage,pages-1);$('#evidence-count').textContent=`找到 ${list.length} 条记录；645 条本批证据，另含 ${data.evidence.length-645} 条此前批次引用`;$('#evidence-results').innerHTML=list.slice(evidencePage*pageSize,(evidencePage+1)*pageSize).map(e=>`<button class="evidence-result" data-evidence="${e.id}"><header><span class="audit-id">${e.id}</span><span>${escapeText(e.record||'此前记录')}</span></header><strong>${escapeText(e.title)}</strong><p>${escapeText(e.summary.replace(/\*\*/g,''))}</p></button>`).join('')||'<p class="empty">没有匹配的记录，试试论文名或 E 编号。</p>';$('#evidence-page').textContent=`${evidencePage+1} / ${pages}`;$('#evidence-prev').disabled=evidencePage===0;$('#evidence-next').disabled=evidencePage===pages-1;}
$('#evidence-search').addEventListener('input',()=>{evidencePage=0;renderEvidence();});$('#evidence-prev').addEventListener('click',()=>{evidencePage--;renderEvidence();$('#evidence-count').scrollIntoView({block:'start'});});$('#evidence-next').addEventListener('click',()=>{evidencePage++;renderEvidence();$('#evidence-count').scrollIntoView({block:'start'});});
function filterRefs(){const q=$('#reference-search').value.trim().toLowerCase();let n=0;$$('.mining-reference').forEach(r=>{r.hidden=q&&!r.dataset.refSearch.includes(q);if(!r.hidden)n++;});$('#reference-count').textContent=`显示 ${n} / ${data.refs.length} 条原稿书目记录`;}
$('#reference-search').addEventListener('input',filterRefs);
function filterScreening(){const q=$('#screening-search').value.trim().toLowerCase();let count=0;const tables=$$('#panel-screening .comparison').slice(1);tables.forEach(t=>{const cards=$$('.table-record',t),rows=$$('.table-wrap tbody tr',t);cards.forEach((d,i)=>{const visible=!q||d.textContent.toLowerCase().includes(q);d.hidden=!visible;rows[i].hidden=!visible;if(visible)count++;});});$('#screening-count').textContent=`摘要细目显示 ${count} / 336 条；上方分区汇总保持完整`;}
$('#screening-search').addEventListener('input',filterScreening);filterScreening();
let printStates=[];window.addEventListener('beforeprint',()=>{printStates=$$('#panel-report details,#panel-references details').map(d=>[d,d.open]);printStates.forEach(([d])=>d.open=true);});window.addEventListener('afterprint',()=>printStates.forEach(([d,v])=>d.open=v));$('#print').addEventListener('click',()=>window.print());$('#back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
function progress(){const max=document.documentElement.scrollHeight-innerHeight;$('#reading-progress').style.width=(max>0?scrollY/max*100:0)+'%';$('#back-top').hidden=scrollY<500;if(mode==='report'){let active='chapter-1';$$('.chapter').forEach(c=>{if(c.getBoundingClientRect().top<180)active=c.id;});$$('.chapter-nav a').forEach(a=>a.classList.toggle('current',a.dataset.chapter===active));}}
let pending=false;window.addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(()=>{progress();pending=false;});}},{passive:true});window.addEventListener('resize',progress);
function followHash(){const id=location.hash.slice(1);if(/^chapter-\d+(?:-\d+)?$/.test(id))go(id);else if(id.startsWith('audit-'))go(id,'audit');else if(id.startsWith('reference-'))go(id,'references');}
window.addEventListener('hashchange',followHash);view('overview',false);renderEvidence();filterRefs();followHash();
})();
